### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by MartiBolet** [MartiBolet/Custom_Qt5_Rviz2#1]
Ei, @albertarla, @iggyrrieta.
En principi ja funciona la part del rviz, si podeu testejar que tot vagi a la primera guai.
També si teniu mes temps al` README.md` hi ha un apartat de `Known issues` que no aconsegueixo resoldre, si teniu temps i podeu fer-li un vistazo guai, pero per avui ja en tinc prou.

**Comment by iggyrrieta** [comment]
He solucionat aixo:

- The Grid doesn't change color to yellow or the thickness.
- The connect functions from QSlider makes the program stop without any error.

Crec que no es tindria que fer servir el VisualizationFrame i que hauriem de fer servir el WindowManagerInterface. He estat apunt de conseguiro sense fer servir la modificació de rViz que vas fer pero em peta amb un error de `ItemIdentityException: Material with the name RVIZ/Red already exists`

**Comment by MartiBolet** [comment]
Guai, puc seguir mirant haviam si trobo una manera millor, pero de moment aixi funciona i al `fleet_manager` l'applicació es tanca guai així que no entenc perqué aquí no.
Que per cert, que no funcionesin aqueststes dues coses era qüestió només de treure els espais en blanc?

**Comment by albertarla** [comment]
Issue del problema que no es tancava al apretar la creu solucionat, PR fet. Si falla ja em dius i ho miro.

**Comment by MartiBolet** [comment]
Works and bugs solved in #2 and #3.
