### ISSUE TITLE
can it modify the grid style to arc

### ISSUE THREAD

**Issue by Amazingmum** [MartiBolet/Custom_Qt5_Rviz2#5]
the arc place at different distance

**Comment by MartiBolet** [comment]
Hi, do you want to place the grid with an offset or change the grid style to circular?

**Comment by Amazingmum** [comment]
> Hi, do you want to place the grid with an offset or change the grid style to circular?

all right,i wanna the circular style with an offset which can be modified by user

**Comment by MartiBolet** [comment]
Actually `rviz` doesn't have circular grid style, but maybe someone had made a plugin for it.
And to add an offset of the grid has to be modified the property of the grid like this:
`grid_->subProp("Offset")->subProp("X")->setValue(<float offset>); 
grid_->subProp("Offset")->subProp("Y")->setValue(<float offset>); 
grid_->subProp("Offset")->subProp("Z")->setValue(<float offset>); 
`
And you can add `QSlider` to modify this 3 values.

**Comment by Amazingmum** [comment]
okay , thanks
